services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - RUN_MIGRATIONS=yes
      - INIT_DB=yes
      - DJANGO_PORT=${DJANGO_PORT-8000}
  
  proxy:
    build:
      context: .
      dockerfile: NGINXDockerfile
    environment:
      - DJANGO_PORT=${DJANGO_PORT-8000}
    depends_on:
      - backend
    ports:
      - 80:80

  db:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  app-db-data: