# Generated by Django 3.2.13 on 2022-05-21 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('add_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.supervisor'),
        ),
        migrations.AddField(
            model_name='activity',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.shift'),
        ),
        migrations.AddField(
            model_name='activity',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.team'),
        ),
    ]
