# Generated by Django 3.2.13 on 2022-05-21 23:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер корпуса')),
                ('room', models.IntegerField(verbose_name='Номер комнаты')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Номер смены')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(2100)], verbose_name='Год смены')),
                ('season', models.CharField(choices=[('SUMMER', 'Лето'), ('AUTUMN', 'Осень'), ('WINTER', 'Зима'), ('SPRING', 'Весна')], max_length=255, verbose_name='Сезон')),
                ('date_start', models.DateField(verbose_name='Дата начала смены')),
                ('date_end', models.DateField(verbose_name='Дата конца смены')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Отряд')),
                ('name', models.CharField(max_length=255, verbose_name='Название отряда')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='users.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Общая информация')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('shift', models.ManyToManyField(null=True, to='users.Shift')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Баланс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('bio', models.TextField(verbose_name='Общая информация')),
                ('med_info', models.TextField(verbose_name='Медицинская информация')),
                ('food_info', models.TextField(verbose_name='Информация о питании')),
                ('qr_code', models.ImageField(upload_to='', verbose_name='QR код')),
                ('building_number', models.IntegerField(verbose_name='Номер корпуса')),
                ('room', models.IntegerField(verbose_name='Номер комнаты')),
                ('activities', models.ManyToManyField(related_name='kids', to='add_services.Activity')),
                ('menus', models.ManyToManyField(related_name='kids', to='add_services.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to=settings.AUTH_USER_MODEL)),
                ('Отряд', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids', to='users.team')),
                ('Родитель', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids', to='users.parent')),
                ('Смена', models.ManyToManyField(related_name='kids', to='users.Shift')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
