# Generated by Django 3.2.13 on 2022-05-22 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='Отряд',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='Родитель',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='Смена',
        ),
        migrations.AddField(
            model_name='kid',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids', to='users.parent'),
        ),
        migrations.AddField(
            model_name='kid',
            name='shift',
            field=models.ManyToManyField(blank=True, related_name='kids', to='users.Shift'),
        ),
        migrations.AddField(
            model_name='kid',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids', to='users.team'),
        ),
    ]
