# Generated by Django 3.2.13 on 2022-05-22 02:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_services', '0003_alter_activity_responsible'),
        ('users', '0002_auto_20220522_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, related_name='kids', to='add_services.Activity'),
        ),
        migrations.AddField(
            model_name='kid',
            name='balance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='kid',
            name='menus',
            field=models.ManyToManyField(blank=True, null=True, related_name='kids', to='add_services.Menu'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='shift',
            field=models.ManyToManyField(blank=True, null=True, to='users.Shift'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team'),
        ),
    ]
